### ISSUE TITLE
Travis often fails because scala 2.10.2 is not downloadable.

### ISSUE THREAD

**Issue by sgkim126** [SollmoStudio/beyond#100]
[This test](https://travis-ci.org/SollmoStudio/beyond/builds/31604213) failed, but [the other test](https://travis-ci.org/sgkim126/beyond/builds/31669534) succeeded even though they are the exactly same commit.

```
[error] (beyondAdmin/*:update) sbt.ResolveException: download failed: org.scala-lang#scala-compiler;2.10.2!scala-compiler.jar
```

**Comment by noraesae** [comment]
This may not happen nowadays? If it happens again, let's open again.
