### ISSUE TITLE
Update DB Collection API documentation.

### ISSUE THREAD

**Issue by noraesae** [SollmoStudio/beyond#189]
As I checked in both Wiki and the source codes, the current design of `ScriptableCollection` is quite different than it's described in the Wiki, especially `option` parameters of APIs such as `find`(tbh, I couldn't find an `option` parameter anywhere but in the `find` method of `ScriptableCollection`). May the Wiki page need to be updated?

https://github.com/SollmoStudio/beyond/wiki/Beyond-DB-API-Collection

@sgkim126, please check this.

**Comment by sgkim126** [comment]
Sorry. It's my fault. I nelect update the document.
I'll do it today.

**Comment by noraesae** [comment]
No worries. Thanks.
