### ISSUE TITLE
Some suggestions to enhance JS part.

### ISSUE THREAD

**Issue by noraesae** [SollmoStudio/beyond#194]
- Move from jshint to [ESLint](http://eslint.org). As I've used in my personal projects, ESLint's way better.
- Unify tab sizes of JS files. 2? 4? `\t`?
- Use to Browserify(or Webpack) + NPM instead of RequireJS. The current trend in frontend dev.

Any idea guys?
@sgkim126 @kimchoco @murmur76

**Comment by sgkim126** [comment]
I'm worrying about using npm. Does npm work well with Rhino?

**Comment by sgkim126** [comment]
And do we need Browserify(or Webpack) for what? As I know browserify makes easy to use modules on the browser. And I don't get why we need it.

**Comment by sgkim126** [comment]
I prefer 2 spaces for indent. But I'm not heavy user of JavaScript. So If you prefer the others, I'll follow your opinion.

**Comment by sgkim126** [comment]
Could you explain more about ESLint? What's the cons of the ESLint?

**Comment by noraesae** [comment]
1. We're already using Gulp in our project. NPM will be used with Node.
1. Browserify + NPM provides CommonJS module system, so it may be familiar to Node developers as well. Also it can separate frontend libraries from the project. I think it's not good idea to contain third-party static files like [this](https://github.com/SollmoStudio/beyond/tree/master/modules/admin/public). However, this is kinda a big change, so wouldn't be so necessary. Just suggestion.
1. +1 for 2 spaces for indent. Any idea, @kimchoco?
1. [ESLint has more rules and settings](http://eslint.org/docs/rules/). For example, ESLint can be set to find out a missing space after a `function` keyword like `function()` which should be `function ()`, however JSHint can't.

**Comment by sgkim126** [comment]
Okay, all of your proposal looks good to me

**Comment by noraesae** [comment]
The first two were applied. I'd close the issue, as the last is not essential.
