### ISSUE TITLE
Problem with multi plugins.

### ISSUE THREAD

**Issue by noraesae** [SollmoStudio/beyond#213]
@sgkim126 ,

Currently even though the following config is set in `application.prod.conf` like below, it doesn't override the one in `application.conf`.

In `application.prod.conf`:
```
  plugin {
    paths {
      logicServer = ["/Users/noraesae/Works/company100/beyond/logicServer"]
    }
  }
```

In `application.conf`:
```
  plugin {
    paths {
      example = ["plugins"]
    }
  }
```

It causes an error that `main.js` can't be found when an app is run as production mode and accessed with the plugin path specified in `application.prod.conf`. Can it be fixed with source modification, or should we reconsider the design of the `paths` configuration?

For the detail context, please feel free to ask me or @murmur76.

**Comment by murmur76** [comment]
@sgkim126 have you checked this? Since our logic server has to be integrated with its client this week, i'd like you to look into this issue as soon as you can.

**Comment by sgkim126** [comment]
Sorry, I'll check it untll wednesday morning.

**Comment by sgkim126** [comment]
I think I got the reason.
It's because ```plugin.paths``` is not for overriden, it's for appended.
So although you launch it activated mode, beyond think you want example plugin, and fail to load example plugin, because production mode should use absolute path.

**Comment by sgkim126** [comment]
I pr #214

**Comment by noraesae** [comment]
The patch merged. :+1:
